In [ ]:
!pip install numpy

Numpy is a fundamental library for scientific computing in Python .It provides support for arrays and matrices along with of mathematical function to operate on these data structure.In this lessoon,we will cover basic of Numpy ,focusing on array and vectorized operations

In [12]:
import numpy as np

In [13]:
#creating array using numpy
#creating 1d array
arr1=np.array([1,2,3,4])
print(arr1)
print(type(arr1))
print(arr1.shape) # if 1d in ouput it visible only one digit with comma in this we see 4 with comma


[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [ ]:
#reshaping into 2d array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row and 5 column and here we cannot reshape it into 1,4 or 1,3 or any because it has 5 elements

array([[1, 2, 3, 4, 5]])

In [15]:
#directly creating 2d array
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [ ]:
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])  # 2d array
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [18]:
np.arange(0,10,2) # element start form 0,goes until 10 and difference between element is 2
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.ones((3,4)) # 3 row and 4 column

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#identity matrix
np.eye(3) # 3* 3 matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#attributes of numpy

In [25]:
#numpy vectorise Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])
#element by addition
print("Addition: ",arr1+arr2)

#Element by substraction
print("Substraction: ",arr1-arr2)
#Element by multiplication
print("Multiplication: ",arr1*arr2)
#Element wise divison
print("Divsion: ",arr2/arr1)


Addition:  [11 22 33 44 55]
Substraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Divsion:  [10. 10. 10. 10. 10.]


In [28]:
#Universal Function :-Applied on each array like 1d ,2d...
arr=np.array([2,3,4,5,6])
##squre root
print("Square root: ",np.sqrt(arr))
## Exponential
print("Expo: ",np.exp(arr))
##Sine
print("Sin: ",np.sin(arr))
##natural log
print("Log: ",np.log(arr))

Square root:  [1.41421356 1.73205081 2.         2.23606798 2.44948974]
Expo:  [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
Sin:  [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
Log:  [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [33]:
##slicing and indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n",arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [48]:
arr[0][0] # i have to get 1 first 0 is row and second 0 column number
print(arr[0:2,2:5])


[[3 4]
 [7 8]]


In [47]:
print(arr[1:3,1:3])

[[ 6  7]
 [10 11]]


In [36]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [49]:
#Modifiy array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [51]:
arr[1:]=200
print(arr)

[[100   2   3   4]
 [200 200 200 200]
 [200 200 200 200]]
